debug: false
bot:
  name: "BOT_NAME"
  emoji: "BOT_EMOJI"
slack:
  token: "SLACK_TOKEN_HERE"
aws:
  - region: "AWS_REGION"
    access_key: "AWS_ACCESS_KEY"
    secret_access_key: "AWS_SECRET_ACCESS_KEY"
